---
- hosts: server
  tasks:
  - name: Clone AWX project repo
    git:
      repo: "{{ awx_repo }}"
      dest: "{{ awx_repo_dir }}"
      version: "{{ awx_version }}"
      update: "{{ awx_keep_updated }}"
      force: true
      accept_hostkey: true

  - name: Create needed directories
    become: true
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    loop:
      - "{{ awx_vars.docker_compose_dir }}"
      - "{{ awx_vars.postgres_data_dir }}"

  - name: Paste user values to inventory vars
    ini_file:
      path: "{{ awx_repo_dir }}/installer/inventory"
      section: "all:vars"
      option: "{{ item.key }}"
      value: "{{ item.value }}"
      state: present
      no_extra_spaces: true
    loop: "{{ awx_vars | dict2items }}"
    loop_control:
      label: "{{ item.key }}"

  - name: Do not expose ports if traefik enabled
    ini_file:
      path: "{{ awx_repo_dir }}/installer/inventory"
      section: "all:vars"
      option: "{{ item }}"
      state: absent
    when: awx_vars.awx_web_container_labels is defined and 'traefik.enable=true' in awx_vars.awx_web_container_labels
    loop:
      - 'host_port'
      - 'host_port_ssl'

  - name: Run the AWX installation playbook
    command: ansible-playbook install.yml -i inventory
    args:
      chdir: "{{ awx_repo_dir }}/installer"
