---
### docker
docker_compose_install: true

### traefik
traefik_enable_https: true
traefik_tls_resolver: acme
traefik_host_domainname: "{{ vault_main_domain }}"
traefik_acme_email: "{{ vault_user_email }}"
traefik_acme_domains:
  - main: "*.{{ traefik_host_domainname }}"
    sans: "{{ traefik_host_domainname }}"
traefik_acme_dns_provider: gcloud
traefik_acme_dns_disablepropagationcheck: true  # This undocumented parameter helps to get certs with dnsChallenge on gcloud and duckdns.org
traefik_log_level: ERROR
traefik_env:
  GCE_TTL: '300'
  GCE_POLLING_INTERVAL: '10'
  GCE_SERVICE_ACCOUNT_FILE: "/etc/traefik/gcp_credentials.json"

traefik_provider_docker: true
traefik_basic_auth_user: "{{ vault_basic_auth_user }}"
traefik_basic_auth_pass: "{{ vault_user_pass_htpasswd }}"

traefik_http_routes:
  - name: router
    url: [ "http://{{ ansible_default_ipv4.gateway }}" ]
  - name: jellyfin
    url: [ "http://{{ ansible_default_ipv4.address }}:8096" ]

### media
media_user: mediaserver
media_home: "/opt/{{ media_user }}"
media_dirs:
  - /media/downloads
  - /media/movies
  - /media/series
media_docker_network: public
media_services:
  - name: jellyfin
    image: hotio/jellyfin:release
    volumes: [ "{{ media_home }}/jellyfin:/config", "/media:/media" ]
    network_mode: host
  - name: qbittorrent
    image: hotio/qbittorrent:release
    volumes: [ "{{ media_home }}/qbittorrent:/config", "/media/downloads:/media/downloads"]
    ports: [ "30815:30815", "30815:30815/udp" ]
    traefik_expose: true
    traefik_server_port: '8080'
  - name: jackett
    image: hotio/jackett:release
    volumes: [ "{{ media_home }}/jackett:/config" ]
    traefik_expose: true
  - name: radarr
    image: hotio/radarr:release
    volumes: [ "{{ media_home }}/radarr:/config", "/media:/media" ]
    traefik_expose: true
  - name: sonarr
    image: hotio/sonarr:latest
    volumes: [ "{{ media_home }}/sonarr:/config", "/media:/media" ]
    traefik_expose: true
  - name: minio
    image: minio/minio:latest
    command: "server /data"
    volumes: [ "{{ media_home }}/minio:/data" ]
    env: { MINIO_ACCESS_KEY: "{{ vault_basic_auth_user }}", MINIO_SECRET_KEY: "{{ vault_user_pass }}" }
    traefik_expose: true

### jenkins
jenkins_user: jenkins
jenkins_group: "{{ jenkins_user }}"
jenkins_groups: docker
jenkins_volume: /opt/jenkins
jenkins_image: jenkins/jenkins:lts-jdk11

### awx
awx_repo: https://github.com/ansible/awx.git
awx_repo_dir: "~/.ansible/awx"
awx_version: devel
awx_keep_updated: true
awx_vars:
  docker_compose_dir: /opt/awx/awxcompose
  postgres_data_dir: /opt/awx/pgdocker
  admin_user: "{{ vault_basic_auth_user }}"
  admin_password: "{{ vault_user_pass }}"
  create_preload_data: 'false'
  awx_web_container_labels: '''
    traefik.enable=true,
    traefik.http.routers.awxweb.entrypoints=websecure,
    traefik.http.routers.awxweb.rule=Host(`awx.{{ traefik_host_domainname }}`)'''
