---
### docker
docker_compose_install: true

### traefik
traefik_enable_https: true
traefik_tls_resolver: acme
traefik_host_domainname: "{{ vault_main_domain }}"
traefik_acme_email: "{{ vault_user_email }}"
traefik_acme_dns_provider: duckdns
traefik_env:
  DUCKDNS_TOKEN: "{{ vault_duckdns_token }}"

traefik_provider_docker: true
traefik_dashboard_middlewares: auth-forward@docker

traefik_http_routes:
  - name: router
    url: [ "http://{{ ansible_default_ipv4.gateway }}" ]
    middlewares: auth-forward@docker
  - name: jellyfin
    url: [ "http://{{ ansible_default_ipv4.address }}:8096" ]

media_user: mediaserver
media_home: "/opt/{{ media_user }}"
media_dirs:
  - /media/downloads
  - /media/movies
  - /media/series
media_docker_network: public
media_services:
  - name: jellyfin
    image: jellyfin/jellyfin:latest
    volumes: [ "{{ media_home }}/jellyfin/config:/config", "{{ media_home }}/jellyfin/cache:/cache", "/media:/media" ]
    network_mode: host
  - name: transmission
    image: ghcr.io/linuxserver/transmission:latest
    ports: [ "51413:51413", "51413:51413/udp" ]
    volumes: [ "{{ media_home }}/transmission:/config", "/media/downloads:/downloads", "/media/downloads/watch:/watch", "/media:/media" ]
    env: { USER: "{{ vault_basic_auth_user }}", PASS: "{{ vault_user_pass }}" }
    traefik_expose: true
    traefik_server_port: '9091'
  - name: jackett
    image: ghcr.io/linuxserver/jackett:latest
    volumes: [ "{{ media_home }}/jackett:/config" ]
    traefik_expose: true
  - name: radarr
    image: ghcr.io/linuxserver/radarr:latest
    volumes: [ "{{ media_home }}/radarr:/config", "/media:/media" ]
    traefik_expose: true
  - name: sonarr
    image: ghcr.io/linuxserver/sonarr:preview
    volumes: [ "{{ media_home }}/sonarr:/config", "/media:/media" ]
    traefik_expose: true
