---
### docker
docker_compose_install: true

### traefik
traefik_enable_https: true
traefik_tls_resolver: acme
traefik_host_domainname: "{{ vault_main_domain }}"
traefik_acme_email: "{{ vault_user_email }}"
traefik_acme_domains: [ { main: "*.{{ traefik_host_domainname }}" } ]
traefik_acme_dns_provider: gcloud
traefik_env:
  GCE_POLLING_INTERVAL: '10'
  GCE_PROPAGATION_TIMEOUT: '300'
  GCE_SERVICE_ACCOUNT_FILE: "/etc/traefik/gcp_credentials.json"

traefik_provider_docker: true
traefik_basic_auth_user: "{{ vault_basic_auth_user }}"
traefik_basic_auth_pass: "{{ vault_user_pass_htpasswd }}"

traefik_http_routes:
  - name: router
    url: [ "http://{{ ansible_default_ipv4.gateway }}" ]
  - name: jellyfin
    url: [ "http://{{ ansible_default_ipv4.address }}:8096" ]

### media
media_user: mediaserver
media_home: "/opt/{{ media_user }}"
media_dirs:
  - /media/downloads
  - /media/movies
  - /media/series
media_docker_network: public
media_services:
  - name: jellyfin
    image: jellyfin/jellyfin:latest
    volumes: [ "{{ media_home }}/jellyfin/config:/config", "{{ media_home }}/jellyfin/cache:/cache", "/media:/media" ]
    network_mode: host
  - name: transmission
    image: ghcr.io/linuxserver/transmission:latest
    ports: [ "51413:51413", "51413:51413/udp" ]
    volumes: [ "{{ media_home }}/transmission:/config", "/media/downloads:/downloads", "/media/downloads/watch:/watch", "/media:/media" ]
    env: { USER: "{{ vault_basic_auth_user }}", PASS: "{{ vault_user_pass }}" }
    traefik_expose: true
    traefik_server_port: '9091'
  - name: jackett
    image: ghcr.io/linuxserver/jackett:latest
    volumes: [ "{{ media_home }}/jackett:/config" ]
    traefik_expose: true
  - name: radarr
    image: ghcr.io/linuxserver/radarr:latest
    volumes: [ "{{ media_home }}/radarr:/config", "/media:/media" ]
    traefik_expose: true
  - name: sonarr
    image: ghcr.io/linuxserver/sonarr:preview
    volumes: [ "{{ media_home }}/sonarr:/config", "/media:/media" ]
    traefik_expose: true
  - name: minio
    image: minio/minio:latest
    command: "server /data"
    volumes: [ "{{ media_home }}/minio:/data" ]
    env: { MINIO_ACCESS_KEY: "{{ vault_basic_auth_user }}", MINIO_SECRET_KEY: "{{ vault_user_pass }}" }
    traefik_expose: true

### jenkins
jenkins_user: jenkins
jenkins_group: "{{ jenkins_user }}"
jenkins_groups: docker
jenkins_volume: /opt/jenkins
jenkins_image: jenkins/jenkins:lts-jdk11

### awx
awx_repo: https://github.com/ansible/awx.git
awx_repo_dir: "~/.ansible/awx"
awx_version: devel
awx_keep_updated: true
awx_vars:
  docker_compose_dir: /opt/awx/awxcompose
  postgres_data_dir: /opt/awx/pgdocker
  admin_user: "{{ vault_basic_auth_user }}"
  admin_password: "{{ vault_user_pass }}"
  create_preload_data: 'false'
  awx_web_container_labels: '''
    traefik.enable=true,
    traefik.http.routers.awxweb.entrypoints=websecure,
    traefik.http.routers.awxweb.rule=Host(`awx.{{ traefik_host_domainname }}`)'''
